# Generated by Django 5.0.1 on 2024-03-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_cartmodel_user_alter_cartmodel_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='product_id',
            new_name='product',
        ),
    ]
