# Generated by Django 5.0.1 on 2024-03-13 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_rename_product_id_cartmodel_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='User',
        ),
        migrations.DeleteModel(
            name='cartModel',
        ),
        migrations.DeleteModel(
            name='customerModel',
        ),
    ]
