# Generated by Django 5.0.1 on 2024-03-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_formalmodel_delete_formals_alter_jeans_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalmodel',
            name='image',
            field=models.ImageField(upload_to='formals/'),
        ),
    ]
