# Generated by Django 5.0.1 on 2024-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_alter_formalmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurtasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kurtas/')),
                ('title', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SuitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='suits/')),
                ('title', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TopsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tops/')),
                ('title', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TshirtsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tshirts/')),
                ('title', models.CharField(max_length=100)),
                ('prize', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='jeans',
        ),
        migrations.DeleteModel(
            name='kurtas',
        ),
        migrations.DeleteModel(
            name='tops',
        ),
        migrations.DeleteModel(
            name='tshirts',
        ),
    ]
