# Generated by Django 5.0.1 on 2024-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_kurtasmodel_suitsmodel_topsmodel_tshirtsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalmodel',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='kurtasmodel',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='suitsmodel',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='topsmodel',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='tshirtsmodel',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
