# Generated by Django 5.0.1 on 2024-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_alter_formalmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalmodel',
            name='description',
            field=models.CharField(default='Unwrap the essence of luxury with the Black Temp Tech Check Shirt. Designed for the modern man, this shirt boasts 37.5°C temperature regulation technology, ensuring optimal comfort all day. It has odour protection that adds an extra layer of confidence. The sleek black hue and classic check pattern make a bold statement, while the semi-cutaway collar and India slim fit add a touch of contemporary flair. Crafted with woven fabric, it features full sleeves, a button closure, and a chest pocket for added convenience.\n\n● Removes sweat for active comfort and unmatched style.\n● Pair with Blackberrys trousers for a polished and refined look.\n\nFabric Composition\n70% Cotton, 30% Polyester\nWash Care\nGentle Machine Wash. We Take Pride In Our Premium Quality And Urge You To Follow The Instructions On The Wash Care Label Of The Product For Durability.\n', max_length=10000),
        ),
    ]
