# Generated by Django 5.0.1 on 2024-03-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0015_alter_kurtasmodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirtsmodel',
            name='description',
        ),
    ]
