# Generated by Django 5.0.1 on 2024-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0016_remove_tshirtsmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtsmodel',
            name='description',
            field=models.CharField(default='Make a stylish statement with your looks by donning this Black Polo Neck T-Shirt. The classic polo neck and half sleeves offer a timeless and appealing look, while the slim-fitting silhouette enhances and complements your natural body shape. Crafted in meticulously knitted, this t-shirt is a wardrobe essential embodiment of casual style. The stunning black colour gives your t-shirt a ravishing touch to uplift your overall attire.', max_length=10000),
        ),
    ]
