# Generated by Django 5.0.1 on 2024-03-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0018_alter_formalmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurtasmodel',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='suitsmodel',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='topsmodel',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='tshirtsmodel',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
