# Generated by Django 5.0.1 on 2024-03-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0021_profile_delete_cart_delete_myorders_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
