# Generated by Django 5.0.1 on 2024-03-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0024_alter_profilemodel_profile_image_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='password',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
