# Generated by Django 5.0.1 on 2024-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0025_profilemodel_password_profilemodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
