# Generated by Django 5.0.1 on 2024-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0026_alter_profilemodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
