# Generated by Django 5.0.1 on 2024-03-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0032_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product1',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product3',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product4',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product5',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.formalmodel')),
                ('product2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.tshirtsmodel')),
                ('product3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.suitsmodel')),
                ('product4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.kurtasmodel')),
                ('product5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.topsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.product'),
        ),
    ]
